spring.application.name: restClientExample

restclient:
  clients:
    my-client:
      connection-timeout: PT5s
      response-timeout: PT10s
      idled-timeout: PT100s
      user-agent: compliance-accountdetails
